### ISSUE TITLE
Getting OSError: [Errno 5] EIO in Raspberry Pi Pico

### ISSUE THREAD

**Issue by tsarmie** [PinsonJonas/MPL3115A2_MicroPython#4]
Hi I am getting this error on the Raspberry Pi Pico. Unfortunately I do not have another board to test if this issue will be replicated. 

Here is my code:
```
import machine
import utime

from mpl3115a2 import MPL3115A2

sclpin = machine.Pin(13)
sdapin = machine.Pin(12)

i2c = machine.I2C(0, scl=sclpin, sda=sdapin)

mpl = MPL3115A2(i2c, mode=MPL3115A2.PRESSURE)
ps = mpl.temperature()

print (ps)
```

Output:
```
>>> %Run -c $EDITOR_CONTENT
Traceback (most recent call last):
  File "<stdin>", line 11, in <module>
  File "mpl3115a2.py", line 55, in __init__
OSError: [Errno 5] EIO
>>> 
```

**Comment by PinsonJonas** [comment]
My apologies, I do not have a Raspberry Pi Pico to test on, so I cannot replicate or research your issue.

However, experience tells me it might be an issue with the way the utime library is implemented.

If you have found the solution to this problem, please do open a Pull-request.
